### ISSUE TITLE
Add support for timezone aware datetimes to has_been -function.

### ISSUE THREAD

**Issue by kipe** [kipe/pycron#3]

**Comment by jacobtomlinson** [comment]
I can take a look at this if you like? 

I guess the first step would be that if `dt` hasn't been specified and `since` has a timezone that `dt` should be initialised in the same timezone.

How would you want to handle the case of both `since` and `dt` being passed but only one of them with a timezone? Would you want the other to take on the same timezone or to use the system timezone?

**Comment by kipe** [comment]
Sure, go ahead.

The first case seems logical to me.

If both of them have been defined, I would perhaps just raise `TypeError` the same way this does:
```python
In [12]: datetime.now(tz=utc) > datetime.now()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-a7f8e7aa9002> in <module>()
----> 1 datetime.now(tz=utc) > datetime.now()

TypeError: can't compare offset-naive and offset-aware datetimes

```
